CREATE TABLE [Product].[PRO_Order]
(
	[OR_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [OR_OrderDate] DATETIME NOT NULL, 
    [OR_Status] UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT OR_FK_Status FOREIGN KEY (OR_Status)
    REFERENCES Product.PRO_Status(ST_PK), 
    [OR_User] UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT OR_FK_User FOREIGN KEY (OR_User)
    REFERENCES [User].USE_User(US_PK) 
)
