CREATE TABLE [Product].[PRO_ExtraChoiceProduct]
(
	[EP_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [EP_Extrachoice] UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT EP_FK_ExtraChoice FOREIGN KEY (EP_ExtraChoice)
    REFERENCES Product.PRO_ExtraChoice(EC_PK), 
    [EP_Product] UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT EP_FK_Product FOREIGN KEY (EP_Product)
    REFERENCES Product.PRO_Product(PR_PK)
)
