CREATE TABLE [Product].[PRO_OrderItem]
(
	[OI_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [OI_Quantity] INT NOT NULL, 
    [OI_Product] UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT OI_FK_Product FOREIGN KEY (OI_Product)
    REFERENCES Product.PRO_Product(PR_PK), 
    [OI_Order] UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT OI_FK_Order FOREIGN KEY (OI_Order)
    REFERENCES Product.PRO_Order(OR_PK), 
    [OI_Color] UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT OI_FK_Color FOREIGN KEY (OI_Color)
    REFERENCES Product.PRO_Color(CO_PK), 
    [OI_Size] UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT OI_FK_Size FOREIGN KEY (OI_Size)
    REFERENCES Product.PRO_Size(SI_PK)
)
