CREATE TABLE [Product].[PRO_Images]
(
	[IM_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [IM_ImageURL] NVARCHAR(MAX) NOT NULL, 
    [IM_Product] UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT IM_FK_Product FOREIGN KEY (IM_Product)
    REFERENCES Product.PRO_Product(PR_PK)
)
