CREATE TABLE [Product].[PRO_SizeProduct]
(
	[SP_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [SP_Size] UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT SP_FK_Size FOREIGN KEY (SP_Size)
    REFERENCES Product.PRO_Size(SI_PK), 
    [SP_Product] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT SP_FK_Product FOREIGN KEY (SP_Product)
    REFERENCES Product.PRO_Product(PR_PK)    
)
